---
name: Build and Test Dev Image
on:
  pull_request:
    branches:
    - develop
    types:
    - opened
    - synchronize
    - ready_for_review

jobs:
  run_tests:
    uses: ./.github/workflows/run_tests.yaml

  run_build_and_push:
    uses: ./.github/workflows/build_and_push_image.yaml
    needs: run_tests
    secrets:
      GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
