---
name: Build Prod RC Image
'on':
  pull_request:
    branches:
    - master
    - main
    types:
    - opened
    - synchronize
    - ready_for_review
jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
    - name: Verify merge is develop -> main
      if: github.head_ref != 'develop'
      run: echo "Must merge from develop -> main/master"; exit 1
    - name: Check out GitHub Repo
      if: github.event.pull_request.draft == false && github.head_ref == 'develop'
      with:
        ref: "${{ github.event.pull_request.head.sha }}"
      uses: actions/checkout@v2
    - name: Build and Push to Packages
      if: github.event.pull_request.draft == false && github.head_ref == 'develop'
      env:
        PR: "${{ github.event.pull_request.number }}"
        SHA: "${{ github.event.pull_request.head.sha }}"
        DOCKER_ACTOR: "${{ secrets.GHCR_USERNAME }}"
        DOCKER_TOKEN: "${{ secrets.GHCR_TOKEN }}"
      run: "./.github/workflows/scripts/build_prodrc_pr.sh\n"
